### ISSUE TITLE
binary_sensor command line not displayed in search 'binary'

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/home-assistant.github.io#12265]
## The problem

When searching for"binary" in the integrations page, the binary_sensor command_line https://www.home-assistant.io/integrations/command_line/ doesn't show, nor does it popup when searching for "sensor"

Not sure how tho PR this, so please let me suffice with issuing this here

**Comment by frenck** [comment]
It does not have the Binary Sensor category, hence it doesn't show up.

**Comment by Mariusthvdb** [comment]
ok thanks, Pr'd.

**Comment by frenck** [comment]
Fixed in #12266

**Comment by Mariusthvdb** [comment]
still doesn't pop up:

<img width="945" alt="Schermafbeelding 2020-03-04 om 14 32 20" src="https://user-images.githubusercontent.com/33354141/75884399-0641d500-5e25-11ea-81fe-daf1b1d0d57b.png">

nor at:

<img width="956" alt="Schermafbeelding 2020-03-04 om 14 33 25" src="https://user-images.githubusercontent.com/33354141/75884477-2f626580-5e25-11ea-8755-132ebbadf4cc.png">

**Comment by frenck** [comment]
We have Cloudflare caching, it might take some days for it to pop up.
