### ISSUE TITLE
🔗 Fix broken links on our website

### ISSUE THREAD

**Issue by frenck** [home-assistant/home-assistant.github.io#14663]
## The problem

Our website has been aging a bit over the last couple of years, unfortunately, this means a lot of links to external sites, have broken down. E.g., due to the website no longer exists, the page has moved and a bunch of other reasons. This is unfortunate for the users of our website.

This GitHub issue serves as a placeholder to get all those links fixed (or removed if fixing seems impossible).

**Want to help us out?**

Download [Xenu](http://home.snafu.de/tilman/xenulink.html) (for free) and scan our website for broken links and help us fixing them. 👍 🎖 🎉 🍾 

(Any other tool is allowed as well of course).

**Notes**
- `credits.markdown` is a generated file. Unfortunately, we cannot fix broken links there at this moment.

**Please reference this issue in your PR**.

**Comment by TheCoderNikhil** [comment]
can you tell me in detail what i have to do ?

**Comment by satwik-chowdary** [comment]
I can try doing it

**Comment by klaasnicolaas** [comment]
Let's start scan again 😁

**Comment by frenck** [comment]
@klaasnicolaas I have a scan running, takes a bit.

@TheCoderNikhil Find and fix broken links as described in the issue. Is there a specific part that is not clear about that description?

**Comment by klaasnicolaas** [comment]
@frenck Ehmm....Must admit that the scanner is already running here 🤣 Perhaps useful to indicate that a pull request should not be too large but also not too small? If you know what I mean 😄

**Comment by JeffResc** [comment]
Here are a few URLs that I found that I would like to leave open for someone else to fix:
```
Getting links from: https://www.home-assistant.io/docs/mqtt/
├─BROKEN─ https://www.home-assistant.io/cookbook/python_component_mqtt_basic/ (HTTP_404)

Getting links from: https://www.home-assistant.io/integrations/http/
├─BROKEN─ https://www.home-assistant.io/developers/python_api/ (HTTP_404)
├─BROKEN─ https://www.home-assistant.io/developers/server_sent_events/ (HTTP_404)

Getting links from: https://www.home-assistant.io/integrations/http#hosting-files
├─BROKEN─ https://www.home-assistant.io/developers/python_api/ (HTTP_404)
├─BROKEN─ https://www.home-assistant.io/developers/server_sent_events/ (HTTP_404)
```

**Comment by stefanroelofs** [comment]
> 
> 
> Here are a few URLs that I found that I would like to leave open for someone else to fix:
> 
> ```
> Getting links from: https://www.home-assistant.io/docs/mqtt/
> ├─BROKEN─ https://www.home-assistant.io/cookbook/python_component_mqtt_basic/ (HTTP_404)
> 
> Getting links from: https://www.home-assistant.io/integrations/http/
> ├─BROKEN─ https://www.home-assistant.io/developers/python_api/ (HTTP_404)
> ├─BROKEN─ https://www.home-assistant.io/developers/server_sent_events/ (HTTP_404)
> 
> Getting links from: https://www.home-assistant.io/integrations/http#hosting-files
> ├─BROKEN─ https://www.home-assistant.io/developers/python_api/ (HTTP_404)
> ├─BROKEN─ https://www.home-assistant.io/developers/server_sent_events/ (HTTP_404)
> ```

I fixed them both. Thanks!

**Comment by cwiggs** [comment]
I've found lots of broken links in the blog, is that in scope to fix as well?

e.g.:
```
URL        `/integrations/automatic/'
Name       `automatic docs'
Parent URL https://www.home-assistant.io/blog/2020/05/20/release-110/, line 948, col 209
Real URL   https://www.home-assistant.io/integrations/automatic/
```

**Comment by JeffResc** [comment]
@cwiggs While I am just a fellow contributor and not a maintainer, I don't think most blog posts could fit under this category. Sure, there are some broken links to pages that still exist, but with my quick scan, it looks like many of them come from old integrations that frankly, don't exist anymore. While you can attempt to fix the pages that still exist, I don't know if you'll be able to find exact matches for all of them.

**Comment by klaasnicolaas** [comment]
Yes, the links in the blogs are also part of the scope of this issue.

**Comment by ZuluWhiskey** [comment]
> I've found lots of broken links in the blog, is that in scope to fix as well?
> 
> e.g.:
> 
> ```
> URL        `/integrations/automatic/'
> Name       `automatic docs'
> Parent URL https://www.home-assistant.io/blog/2020/05/20/release-110/, line 948, col 209
> Real URL   https://www.home-assistant.io/integrations/automatic/
> ```

In this regard, is there a list on the website somewhere of all the old/unsupported integrations? Perhaps links like this could be redirected to that page?

If not could be perhaps have a redirect to a page that simply says "This integration is no longer supported" (or similar)? If blog posts are indeed in scope here then this is really the only way I can personally think of doing this other than editing where the original link was and saying something there instead?

**Comment by frenck** [comment]
We simply remove the link in those cases (but leave the link text in place).

**Comment by ZuluWhiskey** [comment]
> We simply remove the link in those cases (but leave the link text in place).

That makes sense to be fair, thanks @frenck 👍

**Comment by TychoWerner** [comment]
Image broken in post 0.28
https://www.home-assistant.io/blog/2016/09/10/notify-group-reload-api-pihole/

Link to image: https://www.home-assistant.io/images/supported_brands/automatic.png
<img width="770" alt="Screenshot 2020-10-05 at 23 09 40" src="https://user-images.githubusercontent.com/34608981/95132352-f0501600-075f-11eb-8bce-4a99699f3b4e.png">

Which also breaks the image on https://www.home-assistant.io/blog/posts/21

**Comment by TychoWerner** [comment]
Image is broken on 0.20
https://www.home-assistant.io/blog/2016/05/21/release-020/

Link to image: https://www.home-assistant.io/images/supported_brands/roku.png
<img width="725" alt="Screenshot 2020-10-05 at 23 11 57" src="https://user-images.githubusercontent.com/34608981/95132640-63f22300-0760-11eb-8bf3-a341953f13e1.png">
Which also breaks the image on https://www.home-assistant.io/blog/posts/23

**Comment by TychoWerner** [comment]
Link in post 0.92 is broken which links to Introduction Integration
https://www.home-assistant.io/blog/2019/04/24/release-92/

<img width="781" alt="Screenshot 2020-10-05 at 23 15 40" src="https://user-images.githubusercontent.com/34608981/95132965-dcf17a80-0760-11eb-9404-5527d24a0e1a.png">

The URL 'https://www.home-assistant.io/integrations/introduction/' doesn't exist anymore.

**Comment by TychoWerner** [comment]
Link in post 0.101 is broken which links to lifx_legacy docs
https://www.home-assistant.io/blog/2019/10/30/release-101/

<img width="688" alt="Screenshot 2020-10-05 at 23 18 06" src="https://user-images.githubusercontent.com/34608981/95133133-1de98f00-0761-11eb-9220-e86bd722abcb.png">

The URL 'https://www.home-assistant.io/integrations/lifx_legacy/' doesn't exist anymore.

**Comment by TychoWerner** [comment]
Image is broken at 0.25 post
https://www.home-assistant.io/blog/2016/07/30/custom-frontend-panels-jupyter-notebooks-directv/

<img width="813" alt="Screenshot 2020-10-05 at 23 19 44" src="https://user-images.githubusercontent.com/34608981/95133273-5a1cef80-0761-11eb-87a7-3f7acc82c1c3.png">
Image URL is 'https://www.home-assistant.io/images/supported_brands/directv.png'

**Comment by TychoWerner** [comment]
Link in post 0.32 is broken which links to iOS
https://www.home-assistant.io/blog/2016/11/05/hacktoberfest-influxdb-weather/

<img width="809" alt="Screenshot 2020-10-05 at 23 21 22" src="https://user-images.githubusercontent.com/34608981/95133371-833d8000-0761-11eb-8a13-c6fa76e7fd19.png">


The URL 'https://www.home-assistant.io/ecosystem/ios/' doesn't exist anymore.
Which also breaks it for https://www.home-assistant.io/blog/posts/20

**Comment by TychoWerner** [comment]
Link in post 0.34 is broken which links to nginx
https://www.home-assistant.io/blog/2016/12/03/remote-websockets-sonarr/

<img width="750" alt="Screenshot 2020-10-05 at 23 24 39" src="https://user-images.githubusercontent.com/34608981/95133706-052da900-0762-11eb-94cd-14cc3dc40f46.png">


The URL 'https://www.home-assistant.io/ecosystem/nginx/' doesn't exist anymore.
Which also breaks it for https://www.home-assistant.io/blog/posts/20

**Comment by frenck** [comment]
Closing this issue, as Hacktoberfest is over!
