### ISSUE TITLE
Conflicting info of examples

### ISSUE THREAD

**Issue by harpaul** [home-assistant/home-assistant.github.io#19211]
### Feedback

In the Configuration section, an example for energy calculation from a Watt-sensor is given “(e.g. a source in W with prefix k and time h would result in kWh)”.

in the examples section it says that only 
`unit_prefix: k`
needs to be defined

### URL

https://www.home-assistant.io/integrations/integration/

### Version

2021.9.2

**Comment by dgomes** [comment]
Don't understand you, could you elaborate ?

**Comment by harpaul** [comment]
I have: Power sensor in [W]
I want: Energy in [kWh]

‚Configuration‘ section writes I need to define:
```
unit_prefix: k
unit_time: h
```

in the ‚Examples‘ section it says that only
`unit_prefix: k`
needs to be defined

**Comment by dgomes** [comment]
`unit_time string (optional, default: h)
`

**Comment by dmshimself** [comment]
I have what seems to be a related example.  I have a sensor for energy imported by my solar invertor which delivers W.  It is shown here:

![1](https://user-images.githubusercontent.com/6901481/132270101-4f24b31e-ad66-43e5-81f0-d09681f24c20.png)

My integration in the config looks like this:

  - platform: integration
    source: sensor.pv_import
    name: energy_imported
    unit_prefix: k
    round: 2
    
The resulting sensor looks like this:
![3](https://user-images.githubusercontent.com/6901481/132270452-bcb47ba3-ca48-4b7c-a6aa-5498a934e5d9.png)

So the unit of measurment is kh rather than as per the example in the documentation of kWh which is needed for the energy management in HA and so cannot be used a feed into the HA energy config.  Is there a way round this?

**Comment by dgomes** [comment]
@dmshimself your issue is unrelated, but has been fixed in 2021.09.4

**Comment by dmshimself** [comment]
Thanks much much for that super fast response and I've upgraded - unfortunately the sensor still doesn't show as usable in Energy.  From the states in developer console, I now get:

state_class: total_increasing
source: sensor.pv_import
unit_of_measurement: kWh
friendly_name: energy_imported
icon: mdi:chart-histogram
device_class: energy

I wondered if the state_class should be 'measurement' as the number of watts from the sensor isn't a total that increases, it's just the value at the current point in time?

**Comment by dgomes** [comment]
Please open a new issue and provide all the requested information

**Comment by harpaul** [comment]
@dgomes thanks for pointing out the 'default', that now makes sense.
I was struggeling with the issue fixed in 2021.09.4, but thought it was a configuration error on my side.

Keep up the good work :)
