### ISSUE TITLE
SMA Solar Integration - missing values

### ISSUE THREAD

**Issue by RealMike1979** [home-assistant/home-assistant.github.io#29116]
### Feedback

The integration of SMA works.

But I can't select the important values ​​in the energy dashboard:
1. Metering_power_absorbed
2. Metering_power_supplied

I can't find/select it in: Settings - Dashboard - Enerie.

But they are received by the inverter in the HA system.

### URL

https://www.home-assistant.io/integrations/sma/

**Comment by rklomp** [comment]
Should be resolved in 2023.10.
Please try beta or wait for the release.

**Comment by chrisss1983** [comment]
Not working in 2023.10.1 either…

**Comment by ziogref** [comment]
I ran into this issue on 2023.10 upgrade to 2023.10.1 still broken, restored backup to 2023.09.3 and its still broken

**Comment by klaasnicolaas** [comment]
https://www.home-assistant.io/docs/energy/faq/#energy-vs-power

Because these entities are not energy entities (different unit of measurement), that's why you can't select them.
