### ISSUE TITLE
Password did not accepted

### ISSUE THREAD

**Issue by ArqamAlkendi** [home-assistant/home-assistant.github.io#41049]
### Feedback

My password is correct and not authorized through home assistant

### URL

https://www.home-assistant.io/integrations/vesync/

### Version

2025.9.4

**Comment by cdnninja** [comment]
2025.10 resolves this.

**Comment by GeuntaBuwono** [comment]
it's got error 500 when I tried to login

**Comment by crypticviper** [comment]
I get the following errors in HA logs. I am not sure if this is related so I didn't create a separate issue.

> 
> 2025-10-03 01:06:02.843 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Levoit for vesync
> Traceback (most recent call last):
>   File "<string>", line 32, in __mashumaro_from_dict__
>   File "<string>", line 9, in __unpack_union_ResponseLoginModel_result__bf62d5ef3a574ad3992791f005a545b1
> mashumaro.exceptions.InvalidFieldValue: Field "result" of type Union[RespLoginTokenResultModel, RespGetTokenResultModel] in ResponseLoginModel has invalid value None
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 761, in __async_setup_with_context
>     result = await component.async_setup_entry(hass, self)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/vesync/__init__.py", line 47, in async_setup_entry
>     await manager.login()
>   File "/usr/local/lib/python3.13/site-packages/pyvesync/vesync.py", line 364, in login
>     return await self._login_token(auth_code=result.authorizeCode)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.13/site-packages/pyvesync/vesync.py", line 416, in _login_token
>     return await self._login_token(region_change_token=result.bizToken)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.13/site-packages/pyvesync/vesync.py", line 403, in _login_token
>     response_model = ResponseLoginModel.from_dict(resp_dict)
>   File "<string>", line 34, in __mashumaro_from_dict__
> mashumaro.exceptions.InvalidFieldValue: Field "result" of type Union[RespLoginTokenResultModel, RespGetTokenResultModel] in ResponseLoginModel has invalid value None
> 2025-10-03 01:06:03.900 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/miio/miot_device.py:23: FutureWarning: functools.partial will be a method descriptor in future Python versions; wrap it in enum.member() if you want to preserve the old behavior
>   Bool = partial(_str2bool)

**Comment by memoxin** [comment]
same errors I also get. 2025.10 HA. I tried removing and adding it again, no luck. sth is broken with login.

**Comment by crypticviper** [comment]
> same errors I also get. 2025.10 HA. I tried removing and adding it again, no luck. sth is broken with login.

Yes, also when I reload the integration I get a email notification from vesync that a login was attempted.

**Comment by GeuntaBuwono** [comment]
I've fixed the issue. You need to change the region to US on the vesync application and reconnect it to home assistance

**Comment by crypticviper** [comment]
> I've fixed the issue. You need to change the region to US on the vesync application and reconnect it to home assistance

Tested it. Works fine for me now. Thank you so much.

**Comment by ArqamAlkendi** [comment]
I'm still facing authentication failures, even after switching to the United States region.

**Comment by GeuntaBuwono** [comment]
> I'm still facing authentication failures, even after switching to the United States region.

Have you upgraded your HA to the latest version?

**Comment by cdnninja** [comment]
As a note this area is for documentation feedback.   Please use this thread: https://github.com/home-assistant/core/issues/153896

**Comment by cdnninja** [comment]
@home-assistant close
